# Site settings
title: SMUNY
header-img: img/home-bg.png
email: sharonymun@gmail.com
copyright_name: smuny
description: > # this means to ignore newlines until "baseurl:"
  God breathed
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  smuny
learn_profile: smuny
email_username: sharonymun@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
